---
title: "Untitled"
author: "Eliza"
date: "8 april 2018"
output: html_document
---

``` {r}
library(rpart)
install.packages("rpart.plot")
install.packages("RColorBrewer")

library(rpart.plot)
library(RColorBrewer)
library(ggplot2)

train = read.csv("train.csv")
test = read.csv("test.csv")


# combine train and test data
test$Survived = rep("None",418)
alldata = rbind(train, test)
attach(alldata)
train$Pclass <- as.factor(train$Pclass)
train$Survived <- as.factor(train$Survived)
alldata$Survived <- as.factor(alldata$Survived)
alldata$Pclass <- as.factor(alldata$Pclass)



# Let us have a look at our data:


table(alldata$Survived) # Much more people died than survived
table(alldata$Pclass)  # Second and First class have a similar amount of people, third has many. 

# Let us visualize this:
# We can see that people from third class had a lower probability of surviving than people from the other classes.

ggplot(data = train, aes(x = Pclass, fill = Survived )) + geom_histogram(stat = "count")

# Also males have a lower probability of surviving ( Women and Children first?)

ggplot(data = train, aes(x = Sex, fill = Survived )) + geom_histogram(stat = "count")

# Let us deal with the name feature

length(unique(as.character(alldata$Name)))  # Are there some names occurring two times?
double.names <- as.character(alldata[which(duplicated(as.character(alldata$Name))),"Name"])
double.names.entries <- alldata[which(as.character(alldata$Name) == double.names[1]|as.character(alldata$Name) == double.names[2]),]

# Some people seem to have the same name, but they are not the same person. 
# Now let us deal with the titles.

Title = sapply(Name, FUN = function(x) {strsplit(as.character(x), split='[,.]')[[1]][2]})
Title = substring(Title, 2)
alldata$Title = as.character(Title)


# That is a lot of titles, lets group them together.


alldata$Title[alldata$Title %in% c("Don", "Jonkheer")] = "Sir"
alldata$Title[alldata$Title %in% c("the Countess", "Lady", "Dona")] = "Lady"
alldata$Title[alldata$Title %in% c("Col", "Capt","Major")] = "Military"

# Let us not overfit, the seem to be the same as their sex and passenger class

alldata$Title[alldata$Title=="Mlle" | alldata$Title=="Ms"] = "Miss"  #We are assuming here that all Ms are not married, maybe consider a change.
alldata$Title[alldata$Title=="Mme"] = "Mrs"

ggplot(data = alldata[1:891,], aes(x= Title, fill = Survived)) + geom_histogram(stat = "count")

# Let us not overfit, the seem to be the same as their sex and passenger class

ind_Tit_F = which(alldata$Title =="Lady")
alldata$Title[ind_Tit] = "Mrs"

ind_Tit_Male = which(alldata$Title =="Rev"|alldata$Title =="Military"|alldata$Title =="Dr"|alldata$Title =="Sir")
alldata$Title[ind_Tit_Male] = "Mr"

alldata$Title = as.factor(alldata$Title)



# Do these titles hold any predicitve power?
ggplot(data = alldata[1:891,], aes(x= Title, fill = Survived)) + geom_histogram(stat = "count")
##
## Maybe leave Rev out later. Maybe also Dr.
##

# Now let us make the plot again and also include the Pclass.
ggplot(data = alldata[1:891,], aes(x= Title, fill = Survived)) + geom_histogram(stat = "count", binwidth = 0.6) + facet_wrap("Pclass")


# Let us turn to the sibspa variable. There is seven different levles of this variable. We will convert it into a factor and take a look at its predictive power.

alldata$SibSp <- as.factor(alldata$SibSp)
ggplot(alldata[1:891,], aes(x = SibSp, fill = Survived)) + geom_histogram(stat= "count", binwidth = 0.6) + facet_wrap(~Pclass+Title)

# We note that travelling with fewer people increases the survival rate in some cases. Especially for Master and Miss. To be able to take this into account, we create a family size variable. 

temp.sibsp <- c(train$SibSp, test$SibSp)
temp.parch <- c(train$Parch, test$Parch)
alldata$FamSize <- as.factor(temp.sibsp+temp.parch+1)

ggplot(alldata[1:891,], aes(x = FamSize, fill = Survived)) + geom_histogram(stat= "count", binwidth = 0.6) + facet_wrap(~Pclass+Title)

# create decks
alldata$Deck = substring(Cabin, 1, 1)
alldata$Deck[alldata$Deck==""] = "U" #unknown
alldata$Deck = as.factor(alldata$Deck)

ggplot(data = alldata,aes(x=as.factor(alldata$Survived), fill=alldata$Title)) + geom_bar(stat="count") 

#alldata$FamSize = as.factor(alldata$SibSp + alldata$Parch)
alldata$FamSize = alldata$SibSp + alldata$Parch

# Fare previous for the whole ticket. Divide it by number of passengers per ticket to get fare per passenger. 
# Travel size defined by number of passengers sharing same ticket number. Similar to FamSize but takes friend groups into account
alldata$FareAdj = rep("", dim(alldata)[1])
alldata$TravelSize = (rep(1, dim(alldata)[1]))
for(ticnr in levels(Ticket)) {
  alldata$FareAdj[alldata$Ticket==ticnr] = signif(alldata$Fare[(alldata$Ticket==ticnr)]/sum(alldata$Ticket==ticnr),4)
  alldata$TravelSize[(alldata$Ticket==ticnr)] =(sum(alldata$Ticket==ticnr))
}
#alldata$TravelSize = as.factor(alldata$TravelSize)
alldata$FareAdj = as.numeric(alldata$FareAdj)
# Deal with missing values
summary(alldata)
# One NA fare
# Regression tree
FareFit = rpart(Fare ~ Sex + Pclass + Title + Deck + Embarked + TravelSize + FamSize, data=alldata[!is.na(alldata$Fare),], method="anova")
alldata$Fare[is.na(alldata$Fare)] = predict(FareFit, newdata=alldata[is.na(alldata$Fare),])
alldata$FareAdj[is.na(alldata$FareAdj)] = alldata$Fare[is.na(alldata$FareAdj)]/sum(alldata$Ticket == alldata$Ticket[is.na(alldata$FareAdj)])

# 263 NA ages
AgeFit = randomForest(Age ~ FareAdj + Title + FamSize, data=alldata[!is.na(alldata$Age),], importance=TRUE, ntrees=500)
alldata$Age[is.na(alldata$Age)] = round(predict(AgeFit, newdata=alldata[is.na(alldata$Age),]))

trainAdj = alldata[!is.na(Survived), c("Survived", "Pclass", "Sex", "Age","Embarked", "Deck", "Title", "FamSize", "FareAdj", "TravelSize")]
testAdj = alldata[is.na(Survived), c("Survived", "Pclass", "Sex", "Age","Embarked", "Deck", "Title", "FamSize", "FareAdj", "TravelSize")]


# double check cross validation for age prediction features ALEX - and check whether features correct
#rfcv(trainAdj[], alldata$Age[!is.na(alldata$Age)], cv.fold=10)

alldata$Age[is.na(alldata$Age)] = predict(AgeFit, newdata=alldata[is.na(alldata$Age),])
varImpPlot(AgeFit)

```

```{r}



# 2 missing embarkation ports
EmbarkedFit = rpart(Embarked ~ Sex + FareAdj + Pclass + Title + Deck + Age + FamSize + TravelSize, data=alldata[alldata$Embarked!="",], method="class", maxdepth=3) # decision tree with max depth of 3 to prevent overfitting
# Only FareAdj relevant (variable importance=49)
#fancyRpartPlot(EmbarkedFit)
alldata$Embarked[which(alldata$Embarked=="")] = predict(EmbarkedFit, newdata=alldata[alldata$Embarked=="",], type="class")

trainAdj = alldata[!is.na(Survived), c("Survived", "Pclass", "Sex", "Age","Embarked", "Deck", "Title", "FamSize", "FareAdj", "TravelSize")]
testAdj = alldata[is.na(Survived), c("Survived", "Pclass", "Sex", "Age","Embarked", "Deck", "Title", "FamSize", "FareAdj", "TravelSize")]

```




``` {r}
SurvivedFit = rpart(as.factor(Survived) ~ ., data = trainAdj, method="class")
fancyRpartPlot(SurvivedFit)
summary(SurvivedFit)
SurvivedFit$variable.importance

pred = predict(SurvivedFit, newdata=testAdj)
submit_tree2 = data.frame(PassengerId = rownames(testAdj), Survived = pred)
write.csv(submit_tree2, "submit_tree2.csv", row.names = FALSE)

# Best with 0.78947 accuracy

```





``` {r}
library(randomForest)
set.seed(100)



ForestFit = randomForest(as.factor(Survived) ~ Title + FareAdj, data=trainAdj, importance=TRUE, ntree=5000)
varImpPlot(ForestFit)

pred = predict(ForestFit, newdata = testAdj)
submit_forest4 = data.frame(passengerId = rownames(testAdj), Survived = pred)
write.csv(submit_forest4, "submit_forest4.csv", row.names=FALSE)

# try to use Title, family and pclass.

```

``` {r} 
# Cross validation
library(ggplot2)
library(caret)
library(doSNOW)
library(e1071)

View(alldata)

train.set.1 = alldata[1:891, c("Pclass", "Title","FareAdj","TravelSize")]
train.set.1$Title <- as.factor(train.set.1$Title)
rf.label <- as.factor(train$Survived)

set.seed(5000)
cross.10 <- createMultiFolds(rf.label, k=3, times = 10)
ctrl.1 <- trainControl(method = "repeatedcv", number = 10, repeats = 10, index = cross.10)

set.seed(2100)

cv.result.1 <- train(x = train.set.1, y = rf.label, method = "rf", tuneLength = 3, ntree = 1000, trControl = ctrl.1 )
#this will take some time
cv.result.1

## will create trian set tomorrow

```


``` {r}
library(party)
set.seed(100)
cForestFit = cforest(as.factor(Survived) ~ ., data=trainAdj, controls = cforest_control(ntree=5000, mtry = 9))

pred = predict(cForestFit, testAdj, OOB=TRUE, type="response")

submit_forest2 = data.frame(PassengerId = rownames(testAdj), Survived = pred)
#write.csv(submit_forest2, "submit_forest2.csv", row.names=FALSE)

# 0.79425 best so far

```

``` {r}
library(gbm)
set.seed(100)
gbm1 = gbm(Survived ??? . , data=trainAdj, distribution="bernoulli", n.trees=10000, cv.folds=5, interaction.depth=4)
best.iter = gbm.perf(gbm1,method="cv")
summary(gbm1, n.trees=best.iter)

pred_boost1 = predict(gbm1, newdata=testAdj, n.trees=best.iter, type="response")
pred_boost1 = round(pred_boost1)

submit_boost1 = data.frame(PassengerId=rownames(testAdj), Survived=pred_boost1)
write.csv(submit_boost1, "submit_boost1.csv", row.names=FALSE)

```


``` {r}
glmFit = glm(Survived ~ ., data=trainAdj, family=binomial)
summary(glmFit)
glmFit = glm(Survived ~ PClass + Age + FamSize, data=trainAdj, family=binomial)

```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
